[package]
name = "mitigate-cli"
description = "Local-first Mitigate MCP command line"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "mitigate"
path = "src/main.rs"

[dependencies]
mitigate-secrets = { path = "../mitigate-secrets", version = "0.1.0" }
mitigate-mcp = { path = "../mitigate-mcp", version = "0.1.0" }
mitigate-gateway = { path = "../mitigate-gateway", version = "0.1.0" }
mitigate-json = { path = "../mitigate-json", version = "0.1.0" }
tokio = { workspace = true, features = ["io-std"] }
mitigate-config = { version = "0.1.0", path = "../mitigate-config" }
mitigate-mcp-scan = { version = "0.1.0", path = "../mitigate-mcp-scan" }
clap.workspace = true
serde.workspace = true
serde_json.workspace = true

[lints]
workspace = true
